spring.application.name=projectflow_db
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/projectflow_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=94a08da1fecbb6e8b46990538cf22d4f8287311ce63125211912440317e08929
jwt.expiration=86400000

# File upload
file.upload-dir=./uploads

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
