server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectflow_db
    username: root
    password: '12345678'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_AT_LEAST_32_CHARS"
    expiration-ms: 86400000